### ISSUE TITLE
Ips to Image

### ISSUE THREAD

**Issue by NX-GoldJust** [friedkeenan/switch-logo-patcher#24]
Hello, do you think it is possible to convert the folder with ips files into the image ?

**Comment by friedkeenan** [comment]
It would in fact be possible, and I have done it quasi-manually in the past. I don't know if there's really much value though in adding that to this tool. Feel free to argue for its addition even after I close this issue, but for now I will be closing it as I do not foresee adding this.

**Comment by impeeza** [comment]
You will need to provide a firmware of one of the IPS files, I normally do this procedure:

Using this table you can know what IPS name correspond to which Firmware:

|    |    |    |
| ---- | ---- | ---- |
|IPS Filename | Offset | Firmware | 
|01890C643E9D6E17B2CDA77A9749ECB9A4F676D6.ips | 1962240 | ??????? | 
|C79F22F18169FCD3B3698A881394F6240385CDB1.ips | 1668164 | 01.00.0 | 
|7C7B8934F26C93BCA6DE78536B373A6C93BB4BD0.ips | 1794304 | 02_00_0 | 
|BE419FD6F1BA24BF5543D94C9A68CAC4C9A34FF1.ips | 1798400 | 02_03_0 | 
|C088ADC91417EBAE6ADBDF3E47946858CAFE1A82.ips | 1962240 | 03_00_0 | 
|3EC573CB22744A993DFE281701E9CBFE66C03ABD.ips | 1716480 | 04_00_0 | 
|7B4123290DE2A6F52DE4AB72BEA1A83D11214C71.ips | 1831168 | 05_00_0 | 
|723DF02F6955D903DF7134105A16D48F06012DB1.ips | 1835264 | 05_01.0 | 
|967F4C3DFC7B165E4F7981373EC1798ACA234A45.ips | 1573120 | 06_00_0 | 
|98446A07BC664573F1578F3745C928D05AB73349.ips | 1589504 | 07_00_0 | 
|0767302E1881700608344A3859BC57013150A375.ips | 1593600 | 08_00_0 | 
|7C5894688EDA24907BC9CE7013630F365B366E4A.ips | 1593600 | 08_01_0 | 
|7421EC6021AC73DD60A635BC2B3AD6FCAE2A6481.ips | 1536256 | 09_00_0 | 
|96529C3226BEE906EE651754C33FE3E24ECAE832.ips | 1544448 | 10_00_0 | 
|D689E9FAE7CAA4EC30B0CD9B419779F73ED3F88B.ips | 1655040 | 11_00_0 | 
|65A23B52FCF971400CAA4198656D73867D7F1F1D.ips | 1655040 | 11_00_1 | 
|B295D3A8F8ACF88CB0C5CE7C0488CC5511B9C389.ips | 1696000 | 12_00_0 | 
|82EE58BEAB54C1A9D4B3D9ED414E84E31502FAC6.ips | 1708288 | 13_00_0 | 
|AFEAACF3E88AB539574689D1458060657E81E088.ips | 1716480 | 14_00_0 & 14_01_0 & 14_01_2 | 
|7E9BB552AAEFF82363D1E8C97B5C6B95E3989E1A.ips | 1704192 | 15_00_0 & 15_0_1 | 
|BA15B407573B8CECF0FAE2B367D3103A2A1E821C.ips | 2191616 | 16_00_0 & 16.0.1 & 16.0.2 & 16.0.3 & 16.1.0 | 
|34D15383767E313EE76F1EE991CD00AD2BF8C62A.ips | 2023680 | 17_0_0 | 
|    |    |    |

You need to extract the original Logo from a set of firmware files in order to get the «main_uncompressed» file of that firmware version, the guide https://gbatemp.net/threads/original-nintendo-logo-from-firmware-switch-logo-patcher.613041/ is well explained

Then you can use the «flips» tool to apply the select IPS file to «main_uncompressed» 

Then open the patched «main_uncompressed» file with a Hexadecimal Editor and extract the data starting on the offset of the table above and a size of 0x69460 (431200) export that data block as «FILE.DATA»

Then you can use GIMP to open «FILE.DATA» file as a RGBAlpha type with size 308*350
Now you have the original image from which the patches was created.
